

DROP TABLE IF EXISTS TRANSACAO;
CREATE TABLE TRANSACAO(
id INT PRIMARY KEY AUTO_INCREMENT,
valor INT,
tipo VARCHAR(255),
descricao VARCHAR(255)
);


DROP TABLE IF EXISTS LIMITE;
CREATE TABLE LIMITE(
id INT PRIMARY KEY AUTO_INCREMENT,
limite INT,
saldo INT
);

--INSERT INTO LIMITE(id, limite, saldo) values (1,1000,1000);
--INSERT INTO LIMITE(id, limite, saldo) values (2,1000,1000);
--INSERT INTO LIMITE(id, limite, saldo) values (3,1000,1000);
